#SPDX-FileCopyrightText: 2017-2024 Enedis
#SPDX-License-Identifier: Apache-2.0

services:
  server:
    image: ghcr.io/enedis-oss/chutney/chutney-server
    container_name: server
    ports:
      - "8081:8443"
    volumes:
      - ../server/.chutney/:/.chutney
    restart: unless-stopped
    environment:
      # https://docs.spring.io/spring-boot/reference/features/external-config.html#features.external-config.typesafe-configuration-properties.relaxed-binding.environment-variables
      CHUTNEY_SECURITY_CORS_ALLOWEDORIGINS_0: https://localhost


  ui:
    image: ghcr.io/enedis-oss/chutney/chutney-ui:latest
    container_name: ui
    ports:
      - "80:80"
      - "443:443"
