#SPDX-FileCopyrightText: 2017-2024 Enedis
#SPDX-License-Identifier: Apache-2.0

version: '3.7'
services:
  server:
    image: ghcr.io/enedis-oss/chutney/chutney-server
    container_name: server
    ports:
      - "8081:8443"
    volumes:
      - ../server/.chutney/:/.chutney
    restart: unless-stopped
  ui:
    image: ghcr.io/enedis-oss/chutney/chutney-ui:latest
    container_name: ui
    ports:
      - "80:80"
      - "443:443"
