#SPDX-FileCopyrightText: 2017-2024 Enedis
#SPDX-License-Identifier: Apache-2.0

blank_issues_enabled: false
contact_links:
  - name: 🙋 Ask Questions, Get Help and Share ideas 💡
    url: https://github.com/Enedis-OSS/chutney/discussions
    about: A place to get help, Q&A, new ideas and discussions
