#SPDX-FileCopyrightText: 2017-2024 Enedis
#SPDX-License-Identifier: Apache-2.0

chutney:
  security:
    users:
      -
        id: admin
        name: admin
        firstname: admin
        lastname: admin
        mail: admin@admin.com
        password: $2a$10$DsdTFU7OMl/HzlGAr4kUUO7ERvOvZPazQiPkuV8a6TM.CXsGrZjoe
        roles:
          - ADMIN
