#SPDX-FileCopyrightText: 2017-2024 Enedis
#SPDX-License-Identifier: Apache-2.0

server:
  port: 8443
  # todo remove http
  http:
    port: 8080
    interface: localhost
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json,text/event-stream
    min-response-size: 1024
  ssl:
    keyStore: 'classpath:security/https/server.jks'
    key-store-password: server
    key-password: server
    trust-store: 'classpath:security/https/truststore.jks'
    trust-store-password: truststore
management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: '*'
        allowed-methods: GET
  endpoint:
    health:
      show-details: always

spring:
  application:
    name: chutney-server
  liquibase:
    change-log: classpath:/changelog/db.changelog-master.xml
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        #generate_statistics: true
        cache:
          use_second_level_cache: true
          use_query_cache: true
          region.factory_class: org.hibernate.cache.jcache.internal.JCacheRegionFactory
        javax:
            cache:
              provider: org.ehcache.jsr107.EhcacheCachingProvider
              uri: ehcache.xml
  profiles:
    active:
      - undertow-https-redirect
      - mem-auth
      - db-sqlite
