#SPDX-FileCopyrightText: 2017-2024 Enedis
#SPDX-License-Identifier: Apache-2.0

name: 'build chutney parent'
description: 'build chutney parent'
inputs:
  goals:
    default: "clean install -V -B"
    description: "Maven goals to execute"
  cache-artifacts:
    default: ""
    description: "path of artifacts to be cached"

runs:
  using: "composite"
  steps:
    - name: Cache node
      uses: actions/cache@v3
      with:
        path: '**/node'
        key: node_cache

    - name: Cache node_modules
      uses: actions/cache@v3
      with:
        path: '**/node_modules'
        key: node_module_cache

    - uses: actions/checkout@v4

    - name: Add the current IP address, long hostname and short hostname record to /etc/hosts file
      if: ${{ ! contains(inputs.goals, '-DskipTests') }}
      shell: bash
      run: |
        echo -e "$(ip addr show eth0 | grep "inet\b" | awk '{print $2}' | cut -d/ -f1)\t$(hostname -f) $(hostname -s)" | sudo tee -a /etc/hosts

    - name: Build chutney parent
      shell: bash
      run: |
        echo "Running: ${{inputs.goals}}"
        mvn ${{ inputs.goals }}

    - name: Temporarily cache jar artifacts
      if: inputs.cache-artifacts != ''
      uses: actions/upload-artifact@v4
      with:
        name: chutney-artifacts
        path: |
          pom.xml
          chutney/pom.xml
          chutney/server/pom.xml
          chutney/server/target/chutney-server-*.jar
          kotlin-dsl/pom.xml
          kotlin-dsl/target/chutney-kotlin-dsl-*.jar
          ${{inputs.cache-artifacts}}
        retention-days: 1
        overwrite: true
