#SPDX-FileCopyrightText: 2017-2024 Enedis
#SPDX-License-Identifier: Apache-2.0

name: 'build chutney parent'
description: 'build chutney parent'
inputs:
  goals:
    default: "clean install -V -B"
    description: "Maven goals to execute"

runs:
  using: "composite"
  steps:
    - name: Cache node
      uses: actions/cache@v3
      with:
        path: '**/node'
        key: node_cache

    - name: Cache node_modules
      uses: actions/cache@v3
      with:
        path: '**/node_modules'
        key: node_module_cache

    - uses: actions/checkout@v4

    - name: Downgrade Docker to 28.0.4
      shell: bash
      run: |
        # See https://docs.docker.com/engine/install/ubuntu/.
        
        # Add Docker's official GPG key:
        sudo apt update
        sudo apt install ca-certificates curl
        sudo install -m 0755 -d /etc/apt/keyrings
        sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
        sudo chmod a+r /etc/apt/keyrings/docker.asc
        
        # Add the repository to Apt sources:
        sudo tee /etc/apt/sources.list.d/docker.sources <<EOF
        Types: deb
        URIs: https://download.docker.com/linux/ubuntu
        Suites: $(. /etc/os-release && echo "${UBUNTU_CODENAME:-$VERSION_CODENAME}")
        Components: stable
        Signed-By: /etc/apt/keyrings/docker.asc
        EOF
        
        sudo apt update
        sudo apt-get install -y --allow-downgrades docker-ce-cli=5:28.0.4-1~ubuntu.24.04~noble docker-ce=5:28.0.4-1~ubuntu.24.04~noble

    - name: Add the current IP address, long hostname and short hostname record to /etc/hosts file
      if: ${{ ! contains(inputs.goals, '-DskipTests') }}
      shell: bash
      run: |
        echo -e "$(ip addr show eth0 | grep "inet\b" | awk '{print $2}' | cut -d/ -f1)\t$(hostname -f) $(hostname -s)" | sudo tee -a /etc/hosts

    - name: Build chutney parent
      shell: bash
      run: |
        echo "Running: ${{inputs.goals}}"
        mvn ${{ inputs.goals }}

    - name: Temporarily cache chutney artifacts
      uses: actions/upload-artifact@v4
      with:
        name: chutney-artifacts
        path: /home/runner/.m2/repository/fr/enedis/chutney
        retention-days: 1
        overwrite: true
