#SPDX-FileCopyrightText: 2017-2024 Enedis
#SPDX-License-Identifier: Apache-2.0

# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: 'Chutney'
site_url: https://www.chutney-testing.com/
site_description: Opinionated test tool for Specification by Example
site_author: Chutney Testing Team
repo_name:
repo_url: https://github.com/Enedis-OSS/chutney/
edit_uri: https://github.com/Enedis-OSS/chutney/docs/docs/
copyright: © Chutney Testing 2017 | under the Apache License, Version 2.0

nav:
  - Overview: index.md
  - Getting Started:
      - Demo: getting_started/demo.md
      - Requirements: getting_started/requirements.md
      - Write a scenario: getting_started/write.md
      - Run a scenario: getting_started/run.md
  - Installation:
      - Local Development: installation/local_dev.md
      - On premise:
          - installation/on_premise/introduction.md
          - Minimal configuration: installation/on_premise/minimal_conf.md
          - Further details: installation/on_premise/details.md
      - Advanced topics: installation/advanced_topics.md
  - Documentation:
      - Scenario: documentation/scenario.md
#      - Campaign: documentation/campaign.md
      - Dataset: documentation/dataset.md
#      - Environment: documentation/environment.md
      - Synchronize: documentation/synchronize.md
      - Actions:
          - documentation/actions/introduction.md
          - Assertions: documentation/actions/assertions.md
          - Context: documentation/actions/context.md
          - HTTP: documentation/actions/http.md
          - AMQP: documentation/actions/amqp.md
          - SQL: documentation/actions/sql.md
          - JMS / Jakarta: documentation/actions/jms.md
          - Kafka: documentation/actions/kafka.md
          - Selenium: documentation/actions/selenium.md
          - SCP / FTP / SSH: documentation/actions/ssh.md
          - MongoDB: documentation/actions/mongo.md
          - Micrometer: documentation/actions/micrometer.md
          - Radius: documentation/actions/radius.md
          - SOAP: documentation/actions/soap.md
          - Groovy: documentation/actions/groovy.md
      - Functions:
          - documentation/functions/introduction.md
          - Random values: documentation/functions/generate.md
          - Dates & Time: documentation/functions/datetime.md
          - JSON: documentation/functions/json.md
          - XPath: documentation/functions/xpath.md
          - Network: documentation/functions/network.md
          - Classpath: documentation/functions/classpath.md
          - Escape: documentation/functions/escape.md
          - Handling null: documentation/functions/nullable.md
          - Micrometer: documentation/functions/micrometer.md
          - String: documentation/functions/string.md
          - Wiremock: documentation/functions/wiremock.md
          - SOAP: documentation/functions/soap.md
          - Math: documentation/functions/math.md
#      - Strategies:
#          - documentation/strategies/introduction.md
#          - Default: documentation/strategies/default.md
#          - Retry: documentation/strategies/retry.md
#          - Soft: documentation/strategies/soft.md
#          - Foreach: documentation/strategies/foreach.md
#          - If: documentation/strategies/if.md
      - Extension:
          - Action: documentation/extension/action.md
          - Function: documentation/extension/function.md
#          - Strategy: documentation/extension/strategy.md
      - Idea Plugin: documentation/intellij_plugin.md

extra_css:
  - stylesheets/extra.css

theme:
  name: material
  favicon: img/favicon.ico
  logo: img/logo.png
  language: en
  font:
    text: Ubuntu
    #text: Montserrat
    code: Source Code Pro
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch
        # icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        # icon: material/weather-sunny
        name: Switch to light mode
  features:
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - navigation.tracking
    - navigation.tabs
    - navigation.expand
    - navigation.indexes
#    - header.autohide

# Material theme specific
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/chutney-testing

markdown_extensions:
  - toc:
      permalink: "🔗"
      baselevel: 2
      toc_depth: 3
  - footnotes
  - admonition
  - pymdownx.highlight:
      linenums: true
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - search
  - git-revision-date-localized
  - redirects:
        redirect_maps:
          'install.md': 'index.md'   # to be removed after fixing in chutney

validation:
  links:
    absolute_links: relative_to_docs
    anchors: warn
    unrecognized_links: warn
