#SPDX-FileCopyrightText: 2017-2024 Enedis
#SPDX-License-Identifier: Apache-2.0

name: "Debug release to Maven Central"

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    uses: ./.github/workflows/build-all-template.yml
    with:
      skipTests: true
      cache-artifacts: |
        idea-plugin/build/distributions/*.zip

  release-github:
    needs: [ build ]
    uses: ./.github/workflows/release-github-debug-template.yml
    with:
      publish-to-github-maven-registry: false
