#SPDX-FileCopyrightText: 2017-2024 Enedis
#SPDX-License-Identifier: Apache-2.0

name: "Release to Maven Central"

on:
  push:
    tags:
      - '[1-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    uses: ./.github/workflows/build-all-template.yml
    with:
      skipTests: true
      cache-artifacts: |
        chutney/server/target/server-*-boot.jar
        idea-plugin/build/distributions/*.zip
        chutney/ui/dist

  release-github:
    needs: [ build ]
    uses: ./.github/workflows/release-github-template.yml
    with:
      publish-to-github-maven-registry: false

  release-to-central:
    needs: [ build ]
    uses: ./.github/workflows/build-all-template.yml
    with:
      release: true
      server-id: central
    secrets:
      gpg-private-key: ${{secrets.CHUTNEY_GPG_PRIVATE_KEY}}
      gpg-passphrase: ${{ secrets.CHUTNEY_GPG_PASSPHRASE }}
      gpg-key-id: ${{ secrets.CHUTNEY_GPG_KEY_ID }}
      maven-username: ${{ secrets.MAVEN_USER_TOKEN }}
      maven-password: ${{ secrets.MAVEN_PASSWORD_TOKEN }}

  release-docker:
    needs: [ build ]
    uses: ./.github/workflows/release-docker-template.yml
    with:
      version: ${{needs.build.outputs.PROJECT_VERSION}}
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
